### ISSUE TITLE
Github pages not working

### ISSUE THREAD

**Issue by Suman-Jaiswal** [Suman-Jaiswal/Webd#1]
L

**Comment by E13ctron** [comment]
Maybe it might be because you gave root folder (in settings) for github, So instead give the directory which contains the index.html
@Suman-Jaiswal

**Comment by Suman-Jaiswal** [comment]
done bro @Amar-2003

**Comment by E13ctron** [comment]
@Suman-Jaiswal Go and study xD

**Comment by Suman-Jaiswal** [comment]
sed lyf @Amar-2003

**Comment by E13ctron** [comment]
Cool life, everything requires a limit xD @Suman-Jaiswal

**Comment by Suman-Jaiswal** [comment]
hehe, I didn't get you. What are you saying about the limit?

**Comment by E13ctron** [comment]
@Suman-Jaiswal , Keep everything under a limit

**Comment by E13ctron** [comment]
Well we have used Issues for chating rather than posting issues xD @Suman-Jaiswal

**Comment by Suman-Jaiswal** [comment]
hehe, ok let's end the episode here XD
